### ISSUE TITLE
Login for Compliance Auditor

### ISSUE THREAD

**Issue by ethanrowe5379** [ethanrowe5379/Brightsolid_Project#1]
As a Compliance Auditor, I want to be able to log into the Compliance dashboard and access all the tools I can as an auditor, so that I get access to the dashboard.

**Comment by JohnHarrow** [comment]
# Definition of Done

## Back End:
- [] Something

## Front End:
- [] Something

## Roadblocks:

**Comment by DanielJakubek** [comment]
ToDo: Make the page more responsive and add BrightSolid colour scheme,

**Comment by DanielJakubek** [comment]
On developmental.
