### ISSUE TITLE
Create Exceptions as Compliance Manger

### ISSUE THREAD

**Issue by DanielJakubek** [ethanrowe5379/Brightsolid_Project#10]
As a Compliance Manager, I want to be able to create new exceptions and set their justifications and the next review date and save the name of the compliance manager that created the exception, so that I can add new exceptions.

**Comment by JohnHarrow** [comment]
# Definition of Done

###  **Back End:**
- [ ] Get all of the cloud resources names from storage
- [ ] Get all of the cloud resource compliance statuses from storage
- [ ] Create a new exception record
- [ ] Add the justification to the record
- [ ] Add the review date to the record
- [ ] Add the Compliance Manager's name to the record


###  **Front End:**
- [ ] Display each of the cloud resources
- [ ] Display the compliance status of each cloud resource
- [ ] Add a button to add an exception
- [ ] Add a text box to add the justification
- [ ] Add a text box or drop-down menu for adding the review date
- [ ] Add a button to submit the exception



###  **Roadblocks:**

**Comment by DanielJakubek** [comment]
On developmental.
