### ISSUE TITLE
Viewing Compliance dashboard as Auditor

### ISSUE THREAD

**Issue by ethanrowe5379** [ethanrowe5379/Brightsolid_Project#2]
As a Compliance Auditor, I want to be able to view a Top-level view of compliance rules linked to my company, so that I can view all the rules.

**Comment by JohnHarrow** [comment]
# Definition of Done

###  **Back End:**
- [ ] Get the status of each of the compliance rules from storage



###  **Front End:**
- [ ] Display all of the compliance rules
- [ ] Display the status of each of the compliance rules
- [ ] Add link to detailed report for each of the compliance rules



###  **Roadblocks:**

**Comment by DanielJakubek** [comment]
On developmental.
