### ISSUE TITLE
Create Database issues

### ISSUE THREAD

**Issue by JFergus98** [ethanrowe5379/Brightsolid_Project#20]
Here are a few problems I ran into when initialising the Database:
- [x] Need to figure out what datatype to best to use for the "timestampz" variables, it currently set to _varchar_.
- [x] Need to ask the client about what datatype "last_updated_by" is supposed to be, currently set to _int_ but could possibly be _varchar_.
- [x] Need to ask client if this is a necessary variable, if it is a primary key will need to be created in the "non_complience" table.
- [x] Need to check datatype for JSON metadata, _longblob_ is usually large enough, however there might be a better datatype to use.

**Comment by DanielJakubek** [comment]
All has been figured out. For the last issue here, we do not work with the resource table in such a manner that we need work with JSONs.
