### ISSUE TITLE
Access denied for loading data from csv files

### ISSUE THREAD

**Issue by JFergus98** [ethanrowe5379/Brightsolid_Project#22]
I ran into some errors why trying to read the data from the csv into my database. So currently the csvInsets Script does not work.

![image](https://user-images.githubusercontent.com/55389749/193397025-9ab4aa17-6b0e-4332-9230-26c626ee0d17.png)

**Comment by DanielJakubek** [comment]
We figured out a way around this by uploading csv files individually, takes longer but works.
