### ISSUE TITLE
View compliance rule detailed view as Auditor

### ISSUE THREAD

**Issue by DanielJakubek** [ethanrowe5379/Brightsolid_Project#3]
As a compliance Auditor, I want to be able to view a report of each compliance rule, so that I can get more detail on it.

**Comment by JohnHarrow** [comment]
# Definition of Done

###  **Back End:**
- [ ] Get all of the cloud resources names from storage
- [ ] Get all of the cloud resource compliance statuses from storage


###  **Front End:**
- [ ] Display each of the cloud resources
- [ ] Display the compliance status of each cloud resource


###  **Roadblocks:**

**Comment by DanielJakubek** [comment]
On developmental.
