### ISSUE TITLE
Login for Compliance Manager

### ISSUE THREAD

**Issue by DanielJakubek** [ethanrowe5379/Brightsolid_Project#6]
As a Compliance Manager, I want to be able to log into the Compliance dashboard and access all the tools I can as a manager, so that I get access to the dashboard.

**Comment by JohnHarrow** [comment]
# Definition of Done

###  **Back End:**
- [ ] Add functionality to compare username and password to that of those in database
- [ ] Add some sort of encryption to the stored usernames and passwords?
- [ ] Add some sort of function to encrypt the input for comparison to the database?
- [ ] Add functionality that shows the correct page for the Compliance Manager


###  **Front End:**
- [ ] Add an input box for a username
- [ ] Add an input box for the password
- [ ] Add a submit button
- [ ] Page layout for login page


###  **Roadblocks:**

**Comment by DanielJakubek** [comment]
ToDo: Make the page more responsive and add BrightSolid colour scheme,

**Comment by DanielJakubek** [comment]
On developmental.
