### ISSUE TITLE
View Any exceptions as Compliance Manager.

### ISSUE THREAD

**Issue by DanielJakubek** [ethanrowe5379/Brightsolid_Project#9]
As a Compliance Manager, I want to be able to view all exceptions, so that I can view their report detailing justifications, next review date and the name of the compliance manager that set the exception.

**Comment by JohnHarrow** [comment]
# Definition of Done

###  **Back End:**
- [ ] Get the name of each of the cloud resources that has been excepted 
- [ ] Get the text justification for each of the exceptions 
- [ ] Get the next review date for each of the exceptions 
- [ ] Get the name of the compliance manager for each of the exceptions


###  **Front End:**
- [ ] Display all of the exceptions
- [ ] Display the text justification for each of the exceptions
- [ ] Display the next review date for each of the exceptions
- [ ] Display the name of the compliance manager that set the exception



###  **Roadblocks:**

**Comment by DanielJakubek** [comment]
On developmental.
